export const CONSTANTS = {
    USER_AUTH_REQUEST_START: "USER_AUTH_REQUEST_START",
    USER_AUTH_REQUEST_SUCCESS: "USER_AUTH_REQUEST_SUCCESS",
    USER_AUTH_REQUEST_ERROR: "USER_AUTH_REQUEST_ERROR",
    USER_REGISTER_REQUEST_START: "USER_REGISTER_REQUEST_START",
    USER_REGISTER_REQUEST_SUCCESS: "USER_REGISTER_REQUEST_SUCCESS",
    USER_REGISTER_REQUEST_ERROR: "USER_REGISTER_REQUEST_ERROR",
    LOGOUT: "LOGOUT",
    ADD_CARD: "ADD_CARD",
    DRAG_HAPPENED: "DRAG_HAPPENED",
    EDIT_CARD: "EDIT_CARD",
    DELETE_CARD: "DELETE_CARD",

};

